# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="target_type",
            field=models.CharField(blank=True, max_length=64, verbose_name="目标类型"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="目标后台 ID"
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_code",
            field=models.CharField(blank=True, max_length=128, verbose_name="目标编码"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="目标名称"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="audit_opera_target__f440b1_idx",
            ),
        ),
    ]
