# Generated by Django 6.0.6 on 2026-07-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0012_backfill_data_taxonomy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="成果名称")),
                ("description", models.TextField(blank=True, verbose_name="成果说明")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("analysis", "平台分析成果"),
                            ("direct_import", "直接导入成果"),
                        ],
                        default="direct_import",
                        max_length=24,
                        verbose_name="成果来源",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("map", "地图"),
                            ("chart", "图表"),
                            ("report", "报告"),
                            ("table", "表格"),
                            ("image", "图片"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="成果类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="提供单位"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="成果文件路径"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="媒体类型"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="result_artifacts",
                        to="auth.group",
                        verbose_name="可访问角色",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_artifacts",
                        to="catalog.dictionaryitem",
                        verbose_name="权威业务分类",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_artifacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_result_artifacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "成果文件",
                "verbose_name_plural": "成果文件",
                "ordering": ("-published_at", "-updated_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "source_type"],
                        name="catalog_res_status_687d5b_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="catalog_res_categor_4f4c0b_idx",
                    ),
                ],
            },
        ),
    ]
